Question Number-2

In [1]:
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 12.2 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2024.12.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which i

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("paultimothymooney/poetry")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/poetry


In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from datasets import load_dataset
from transformers import GPT2TokenizerFast, DataCollatorForLanguageModeling

In [4]:
# Load the lyrics file for the chosen artist
file_path = "/kaggle/input/poetry/Kanye_West.txt"  # Load the chosen artist/band file
with open(file_path, 'r', encoding='utf-8') as file:
    text = file.read()
    #print(f"Total words (unique tokens): {text}")

In [5]:
# Initialize the tokenizer
model_id = "gpt2-medium"
tokenizer = GPT2TokenizerFast.from_pretrained(model_id)

# Define constants
MAX_LENGTH = 256
BATCH_SIZE = 2  # Define the batch size

# Tokenize the entire corpus
tokenized_data = tokenizer(
    text,
    truncation=True,
    max_length=MAX_LENGTH,
    return_overflowing_tokens=True,
    return_length=True
)

# Check the tokenized data
print(tokenized_data)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

{'input_ids': [[171, 119, 123, 29571, 6429, 812, 29095, 812, 198, 3347, 1392, 530, 286, 534, 3988, 1392, 345, 329, 29095, 812, 198, 40, 760, 8276, 5989, 1200, 1104, 329, 530, 286, 465, 3988, 198, 6653, 5156, 285, 1689, 1097, 290, 48083, 318, 5749, 621, 465, 198, 1639, 481, 766, 683, 319, 3195, 597, 1813, 3502, 198, 16643, 262, 3115, 8693, 290, 3708, 572, 287, 257, 47962, 198, 3347, 373, 4385, 284, 2822, 534, 1790, 88, 7039, 1073, 351, 534, 1637, 198, 3347, 1816, 284, 262, 6253, 1392, 10645, 78, 351, 534, 1637, 198, 3347, 6155, 1088, 2045, 588, 3899, 351, 534, 1637, 198, 19926, 303, 1392, 326, 31977, 2269, 3713, 329, 534, 1637, 198, 1532, 345, 257, 600, 645, 22782, 198, 39, 33011, 775, 765, 662, 77, 929, 775, 765, 662, 77, 929, 9425, 198, 20459, 1223, 326, 345, 761, 284, 423, 198, 42323, 618, 673, 2666, 534, 840, 673, 35140, 2666, 351, 2063, 198, 29571, 6429, 812, 29095, 812, 198, 1870, 319, 262, 262, 10955, 339, 1043, 503, 340, 373, 429, 465, 198, 3844, 314, 257, 600, 2282, 345, 257, 3

In [7]:
from transformers import GPT2TokenizerFast

# Load the lyrics file for the chosen artist
file_path = '/kaggle/input/poetry/michael-jackson.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    text = file.read()

# Initialize the tokenizer
model_id = "gpt2-medium"
tokenizer = GPT2TokenizerFast.from_pretrained(model_id)

# Define constants
MAX_LENGTH = 256
BATCH_SIZE = 2  # Define the batch size

# Tokenize the entire corpus
tokenized_data = tokenizer(
    text,
    truncation=True,
    max_length=MAX_LENGTH,
    return_overflowing_tokens=True,
    return_length=True
)

# Check the tokenized data
print(tokenized_data)

{'input_ids': [[198, 198, 58, 4561, 4233, 37219, 47715, 198, 1639, 1683, 765, 1223, 220, 198, 5562, 345, 760, 345, 6584, 470, 423, 220, 198, 464, 517, 345, 760, 345, 6584, 470, 423, 340, 11, 220, 198, 464, 517, 345, 765, 340, 220, 198, 1870, 788, 530, 1110, 345, 651, 340, 11, 220, 198, 1026, 338, 523, 922, 1165, 220, 198, 1537, 340, 338, 655, 588, 616, 2576, 220, 198, 2215, 673, 338, 1088, 502, 220, 198, 40, 655, 1254, 523, 922, 11, 523, 922, 220, 198, 1537, 826, 783, 314, 655, 1254, 4692, 11, 523, 4692, 220, 198, 11028, 866, 284, 616, 11945, 220, 198, 6, 42323, 267, 1219, 986, 220, 198, 32, 259, 470, 645, 34488, 618, 673, 338, 3750, 220, 198, 1026, 338, 407, 5814, 618, 673, 338, 1497, 220, 198, 32, 259, 470, 645, 34488, 618, 673, 338, 3750, 220, 198, 1870, 673, 338, 1464, 3750, 1165, 890, 220, 198, 7149, 2435, 673, 2925, 1497, 220, 198, 198, 42337, 428, 640, 810, 673, 338, 3750, 220, 198, 42337, 611, 673, 338, 3750, 284, 2652, 220, 198, 32, 259, 470, 645, 34488, 618, 673, 338, 3750, 2

In [8]:
def preprocess(example):
    try:
        outputs = tokenizer(
            example,
            truncation=True,
            max_length=MAX_LENGTH,
            return_overflowing_tokens=True,
            return_length=True,
        )
        input_batch = []
        for length, input_ids in zip(outputs["length"], outputs["input_ids"]):
            if length == MAX_LENGTH:
                input_batch.append(input_ids)
                valid_input_ids = input_ids
        if len(input_batch) != 0:
            for i in range(BATCH_SIZE - len(input_batch)):
                input_batch.append(valid_input_ids)
    except Exception as e:
        input_batch = []
    return {"input_ids": input_batch}

preprocessed_data = preprocess(text)
print(preprocessed_data)

{'input_ids': [[198, 198, 58, 4561, 4233, 37219, 47715, 198, 1639, 1683, 765, 1223, 220, 198, 5562, 345, 760, 345, 6584, 470, 423, 220, 198, 464, 517, 345, 760, 345, 6584, 470, 423, 340, 11, 220, 198, 464, 517, 345, 765, 340, 220, 198, 1870, 788, 530, 1110, 345, 651, 340, 11, 220, 198, 1026, 338, 523, 922, 1165, 220, 198, 1537, 340, 338, 655, 588, 616, 2576, 220, 198, 2215, 673, 338, 1088, 502, 220, 198, 40, 655, 1254, 523, 922, 11, 523, 922, 220, 198, 1537, 826, 783, 314, 655, 1254, 4692, 11, 523, 4692, 220, 198, 11028, 866, 284, 616, 11945, 220, 198, 6, 42323, 267, 1219, 986, 220, 198, 32, 259, 470, 645, 34488, 618, 673, 338, 3750, 220, 198, 1026, 338, 407, 5814, 618, 673, 338, 1497, 220, 198, 32, 259, 470, 645, 34488, 618, 673, 338, 3750, 220, 198, 1870, 673, 338, 1464, 3750, 1165, 890, 220, 198, 7149, 2435, 673, 2925, 1497, 220, 198, 198, 42337, 428, 640, 810, 673, 338, 3750, 220, 198, 42337, 611, 673, 338, 3750, 284, 2652, 220, 198, 32, 259, 470, 645, 34488, 618, 673, 338, 3750, 2

In [9]:
# Convert the tokenized data into a list
input_ids = preprocessed_data['input_ids']
dataset_list = [{'input_ids': input_id} for input_id in input_ids]

# Check the length of the dataset
num_train_steps = len(dataset_list) * BATCH_SIZE
print(f'Number of training steps: {num_train_steps}')

Number of training steps: 594


In [10]:
import tensorflow as tf

# Convert the list back to a TensorFlow dataset
tf_train_dataset = tf.data.Dataset.from_generator(
    lambda: (example for example in dataset_list),
    output_signature={
        'input_ids': tf.TensorSpec(shape=(MAX_LENGTH,), dtype=tf.int32)
    }
)

# Create batches
tf_train_dataset = tf_train_dataset.batch(BATCH_SIZE).map(lambda x: {
    'input_ids': tf.stack(x['input_ids']),
    'attention_mask': tf.ones([BATCH_SIZE, MAX_LENGTH], dtype=tf.int32),
    'labels': tf.stack(x['input_ids'])
})

# Check the TensorFlow dataset
for i in tf_train_dataset.take(1):
    print(i)

{'input_ids': <tf.Tensor: shape=(2, 256), dtype=int32, numpy=
array([[  198,   198,    58,  4561,  4233, 37219, 47715,   198,  1639,
         1683,   765,  1223,   220,   198,  5562,   345,   760,   345,
         6584,   470,   423,   220,   198,   464,   517,   345,   760,
          345,  6584,   470,   423,   340,    11,   220,   198,   464,
          517,   345,   765,   340,   220,   198,  1870,   788,   530,
         1110,   345,   651,   340,    11,   220,   198,  1026,   338,
          523,   922,  1165,   220,   198,  1537,   340,   338,   655,
          588,   616,  2576,   220,   198,  2215,   673,   338,  1088,
          502,   220,   198,    40,   655,  1254,   523,   922,    11,
          523,   922,   220,   198,  1537,   826,   783,   314,   655,
         1254,  4692,    11,   523,  4692,   220,   198, 11028,   866,
          284,   616, 11945,   220,   198,     6, 42323,   267,  1219,
          986,   220,   198,    32,   259,   470,   645, 34488,   618,
          673, 

In [11]:
from transformers import TFGPT2LMHeadModel, create_optimizer

# Load the GPT-2 model
model = TFGPT2LMHeadModel.from_pretrained(model_id)

# Create an optimizer
optimizer, schedule = create_optimizer(
    init_lr=5e-5,
    num_warmup_steps=1_000,
    num_train_steps=num_train_steps
)

# Compile the model
model.compile(optimizer=optimizer)

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/1.52G [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [12]:
import tensorflow as tf

# Convert the list back to a TensorFlow dataset
tf_train_dataset = tf.data.Dataset.from_generator(
    lambda: (example for example in dataset_list),
    output_signature={
        'input_ids': tf.TensorSpec(shape=(MAX_LENGTH,), dtype=tf.int32)
    }
)

# Create batches
tf_train_dataset = tf_train_dataset.batch(BATCH_SIZE).map(lambda x: {
    'input_ids': tf.stack(x['input_ids']),
    'attention_mask': tf.ones([BATCH_SIZE, MAX_LENGTH], dtype=tf.int32),
    'labels': tf.stack(x['input_ids'])  # The labels should be of size [BATCH_SIZE, MAX_LENGTH]
})
# Do not squeeze the labels, as they should have shape (BATCH_SIZE, MAX_LENGTH)
# tf_train_dataset = tf_train_dataset.map(lambda x: {
#     'input_ids': x['input_ids'],
#     'attention_mask': x['attention_mask'],
#     'labels': tf.squeeze(x['labels'], axis=0)  # Remove the extra dimension (axis=0) - THIS IS THE PROBLEM
# })

# Check the TensorFlow dataset
for i in tf_train_dataset.take(1):
    print(i)

{'input_ids': <tf.Tensor: shape=(2, 256), dtype=int32, numpy=
array([[  198,   198,    58,  4561,  4233, 37219, 47715,   198,  1639,
         1683,   765,  1223,   220,   198,  5562,   345,   760,   345,
         6584,   470,   423,   220,   198,   464,   517,   345,   760,
          345,  6584,   470,   423,   340,    11,   220,   198,   464,
          517,   345,   765,   340,   220,   198,  1870,   788,   530,
         1110,   345,   651,   340,    11,   220,   198,  1026,   338,
          523,   922,  1165,   220,   198,  1537,   340,   338,   655,
          588,   616,  2576,   220,   198,  2215,   673,   338,  1088,
          502,   220,   198,    40,   655,  1254,   523,   922,    11,
          523,   922,   220,   198,  1537,   826,   783,   314,   655,
         1254,  4692,    11,   523,  4692,   220,   198, 11028,   866,
          284,   616, 11945,   220,   198,     6, 42323,   267,  1219,
          986,   220,   198,    32,   259,   470,   645, 34488,   618,
          673, 

In [13]:
import time

input_text = "true love shouldn't be this complicated"
input_ids = tokenizer(input_text, return_tensors="tf")["input_ids"]

# Generate text
init_time = time.time()
output_temp = model.generate(input_ids, max_length=256, do_sample=True, temperature=1.0, top_k=50)
print(tokenizer.decode(output_temp[0]))
print(time.time() - init_time)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


true love shouldn't be this complicated [6:10] <Nomad> if you're comfortable with having your head cut off [6:10] <Sylpharillion> If anyone wants I can talk in about how I like to use the phrase "I do not want / will not use it" [6:10] <daddyj> it comes up a lot [6:10] <Sylpharillion> It's probably a better response than "I do" though [6:04] <Sylpharillion> I get the feeling that there would be a backlash from most members of the community who wouldn't know what it would say. [6:05] <@emmaw> lol it's the most fucked up thing i've heard in a long time [6:05] <@emmaw> i guess this kind of thing is acceptable on /tg [6:05] <pizza_dog> http://www.reddit.com/r/KotakuInAction/comments/2ezixm/a_question_about_gamergate_butts_problems/ce9q7cf [6:06] <@emmaw> okay? [6
113.85073685646057
